### PR TITLE
Closes #28

### LINKED ISSUE #28: Create a functionality to remove a song with wrong work

### PR DESCRIPTION
**Pull request by devanshukd04**

### CODE REVIEW

File: src/components/Cards.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+function CardPage(props){
```
Comment (vaibhav1405) [inline src/components/Cards.js:1]: use object destructring

File: src/components/Cards.js [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+    return(
+        <div className="cards">
+            <Card style={{ width: '18rem' }}>
+            <Card.Body>
+                <Card.Title style={{ marginBottom:'30px' }}>{props.song}</Card.Title>
```
Comment (vaibhav1405) [inline src/components/Cards.js:6]: use scss file for styling

**Review by vaibhav1405 — CHANGES_REQUESTED** [review]

**Review by AryanShinde — APPROVED** [review]
